# Lab | Data Structuring and Combining Data

## Challenge 1: Combining & Cleaning Data

In this challenge, we will be working with the customer data from an insurance company, as we did in the two previous labs. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

But this time, we got new data, which can be found in the following 2 CSV files located at the links below.

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv

Note that you'll need to clean and format the new data.

Observation:
- One option is to first combine the three datasets and then apply the cleaning function to the new combined dataset
- Another option would be to read the clean file you saved in the previous lab, and just clean the two new files and concatenate the three clean datasets

In [1]:
# Your code goes here
import pandas as pd

url1 = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
url2 = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv"
url3 = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv"

customer_data = pd.read_csv(url1)
customer_data_2 = pd.read_csv(url2)
customer_data_3 = pd.read_csv(url3)

print("File 1 shape:", customer_data.shape)
print("File 2 shape:", customer_data_2.shape)
print("File 3 shape:", customer_data_3.shape)

print("\nFile 1 columns:")
print(customer_data.columns)

print("\nFile 2 columns:")
print(customer_data_2.columns)

print("\nFile 3 columns:")
print(customer_data_3.columns)

File 1 shape: (4008, 11)
File 2 shape: (996, 11)
File 3 shape: (7070, 11)

File 1 columns:
Index(['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Policy Type', 'Vehicle Class', 'Total Claim Amount'],
      dtype='str')

File 2 columns:
Index(['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Total Claim Amount', 'Policy Type', 'Vehicle Class'],
      dtype='str')

File 3 columns:
Index(['Customer', 'State', 'Customer Lifetime Value', 'Education', 'Gender',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Policy Type', 'Total Claim Amount', 'Vehicle Class'],
      dtype='str')

In [2]:
print("File 2:")
customer_data_2.info()
display(customer_data_2.head())

print("File 3:")
customer_data_3.info()
display(customer_data_3.head())

File 2:
<class 'pandas.DataFrame'>
RangeIndex: 996 entries, 0 to 995
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   996 non-null    str
 1   ST                         996 non-null    str
 2   GENDER                     991 non-null    str
 3   Education                  996 non-null    str
 4   Customer Lifetime Value    992 non-null    str
 5   Income                     996 non-null    int64
 6   Monthly Premium Auto       996 non-null    int64
 7   Number of Open Complaints  996 non-null    str
 8   Total Claim Amount         996 non-null    float64
 9   Policy Type                996 non-null    str
 10  Vehicle Class              996 non-null    str
dtypes: float64(1), int64(2), str(8)
memory usage: 85.7 KB

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Total Claim Amount,Policy Type,Vehicle Class
0,GS98873,Arizona,F,Bachelor,323912.47%,16061,88,1/0/00,633.6,Personal Auto,Four-Door Car
1,CW49887,California,F,Master,462680.11%,79487,114,1/0/00,547.2,Special Auto,SUV
2,MY31220,California,F,College,899704.02%,54230,112,1/0/00,537.6,Personal Auto,Two-Door Car
3,UH35128,Oregon,F,College,2580706.30%,71210,214,1/1/00,1027.2,Personal Auto,Luxury Car
4,WH52799,Arizona,F,College,380812.21%,94903,94,1/0/00,451.2,Corporate Auto,Two-Door Car

File 3:
<class 'pandas.DataFrame'>
RangeIndex: 7070 entries, 0 to 7069
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   7070 non-null   str
 1   State                      7070 non-null   str
 2   Customer Lifetime Value    7070 non-null   float64
 3   Education                  7070 non-null   str
 4   Gender                     7070 non-null   str
 5   Income                     7070 non-null   int64
 6   Monthly Premium Auto       7070 non-null   int64
 7   Number of Open Complaints  7070 non-null   int64
 8   Policy Type                7070 non-null   str
 9   Total Claim Amount         7070 non-null   float64
 10  Vehicle Class              7070 non-null   str
dtypes: float64(2), int64(3), str(6)
memory usage: 607.7 KB

,Customer,State,Customer Lifetime Value,Education,Gender,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Total Claim Amount,Vehicle Class
0,SA25987,Washington,3479.137523,High School or Below,M,0,104,0,Personal Auto,499.200000,Two-Door Car
1,TB86706,Arizona,2502.637401,Master,M,0,66,0,Personal Auto,3.468912,Two-Door Car
2,ZL73902,Nevada,3265.156348,Bachelor,F,25820,82,0,Personal Auto,393.600000,Four-Door Car
3,KX23516,California,4455.843406,High School or Below,F,0,121,0,Personal Auto,699.615192,SUV
4,FN77294,California,7704.958480,High School or Below,M,30366,101,2,Personal Auto,484.800000,SUV

In [3]:
# Check missing values in file 2
customer_data_2.isna().sum()

Customer                     0
ST                           0
GENDER                       5
Education                    0
Customer Lifetime Value      4
Income                       0
Monthly Premium Auto         0
Number of Open Complaints    0
Total Claim Amount           0
Policy Type                  0
Vehicle Class                0
dtype: int64

In [4]:
print("File 3:")
customer_data_3.info()

display(customer_data_3.head())

# Check missing values in file 3
customer_data_3.isna().sum()

File 3:
<class 'pandas.DataFrame'>
RangeIndex: 7070 entries, 0 to 7069
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   7070 non-null   str
 1   State                      7070 non-null   str
 2   Customer Lifetime Value    7070 non-null   float64
 3   Education                  7070 non-null   str
 4   Gender                     7070 non-null   str
 5   Income                     7070 non-null   int64
 6   Monthly Premium Auto       7070 non-null   int64
 7   Number of Open Complaints  7070 non-null   int64
 8   Policy Type                7070 non-null   str
 9   Total Claim Amount         7070 non-null   float64
 10  Vehicle Class              7070 non-null   str
dtypes: float64(2), int64(3), str(6)
memory usage: 607.7 KB

,Customer,State,Customer Lifetime Value,Education,Gender,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Total Claim Amount,Vehicle Class
0,SA25987,Washington,3479.137523,High School or Below,M,0,104,0,Personal Auto,499.200000,Two-Door Car
1,TB86706,Arizona,2502.637401,Master,M,0,66,0,Personal Auto,3.468912,Two-Door Car
2,ZL73902,Nevada,3265.156348,Bachelor,F,25820,82,0,Personal Auto,393.600000,Four-Door Car
3,KX23516,California,4455.843406,High School or Below,F,0,121,0,Personal Auto,699.615192,SUV
4,FN77294,California,7704.958480,High School or Below,M,30366,101,2,Personal Auto,484.800000,SUV

Customer                     0
State                        0
Customer Lifetime Value      0
Education                    0
Gender                       0
Income                       0
Monthly Premium Auto         0
Number of Open Complaints    0
Policy Type                  0
Total Claim Amount           0
Vehicle Class                0
dtype: int64

In [6]:
import os

os.listdir()

['.DS_Store',
 '.git',
 'data_cleaning.py',
 'lab-dw-data-structuring-and-combining.ipynb',
 'README.md']

In [7]:
import data_cleaning

In [8]:
customer_data = data_cleaning.clean_column_names(customer_data)
customer_data_2 = data_cleaning.clean_column_names(customer_data_2)
customer_data_3 = data_cleaning.clean_column_names(customer_data_3)

In [9]:
print(customer_data.columns)
print(customer_data_2.columns)
print(customer_data_3.columns)

Index(['customer', 'state', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'vehicle_class', 'total_claim_amount'],
      dtype='str')
Index(['customer', 'state', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'total_claim_amount', 'policy_type', 'vehicle_class'],
      dtype='str')
Index(['customer', 'state', 'customer_lifetime_value', 'education', 'gender',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'total_claim_amount', 'vehicle_class'],
      dtype='str')

In [10]:
customer_data_2.isna().sum()

customer                     0
state                        0
gender                       5
education                    0
customer_lifetime_value      4
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
total_claim_amount           0
policy_type                  0
vehicle_class                0
dtype: int64

In [11]:
# Check categorical values in file 2
for column in ["gender", "state", "education", "policy_type", "vehicle_class"]:
    print("\nFile 2 -", column)
    print(customer_data_2[column].value_counts(dropna=False))

# Check categorical values in file 3
for column in ["gender", "state", "education", "policy_type", "vehicle_class"]:
    print("\nFile 3 -", column)
    print(customer_data_3[column].value_counts(dropna=False))

File 2 - gender
gender
F         527
M         461
NaN         5
female      2
Male        1
Name: count, dtype: int64

File 2 - state
state
Oregon        303
California    277
Arizona       142
Nevada        125
Washington    100
AZ             49
Name: count, dtype: int64

File 2 - education
education
College                 311
High School or Below    290
Bachelor                243
Master                   86
Doctor                   49
Bachelors                17
Name: count, dtype: int64

File 2 - policy_type
policy_type
Personal Auto     756
Corporate Auto    196
Special Auto       44
Name: count, dtype: int64

File 2 - vehicle_class
vehicle_class
Four-Door Car    519
Two-Door Car     211
SUV              174
Sports Car        55
Luxury SUV        21
Luxury Car        16
Name: count, dtype: int64

File 3 - gender
gender
F    3576
M    3494
Name: count, dtype: int64

File 3 - state
state
California    2544
Oregon        1978
Arizona       1302
Nevada         659
Washington     587
Name: count, dtype: int64

File 3 - education
education
Bachelor                2152
College                 2058
High School or Below    2030
Master                   572
Doctor                   258
Name: count, dtype: int64

File 3 - policy_type
policy_type
Personal Auto     5256
Corporate Auto    1535
Special Auto       279
Name: count, dtype: int64

File 3 - vehicle_class
vehicle_class
Four-Door Car    3546
Two-Door Car     1480
SUV              1401
Sports Car        371
Luxury SUV        141
Luxury Car        131
Name: count, dtype: int64

In [12]:
# Inspect customer lifetime value and open complaints in file 2
customer_data_2[
    ["customer_lifetime_value", "number_of_open_complaints"]
].head()

  customer_lifetime_value number_of_open_complaints
0              323912.47%                    1/0/00
1              462680.11%                    1/0/00
2              899704.02%                    1/0/00
3             2580706.30%                    1/1/00
4              380812.21%                    1/0/00

In [13]:
# Inspect customer lifetime value and open complaints in file 3
customer_data_3[
    ["customer_lifetime_value", "number_of_open_complaints"]
].head()

   customer_lifetime_value  number_of_open_complaints
0              3479.137523                          0
1              2502.637401                          0
2              3265.156348                          0
3              4455.843406                          0
4              7704.958480                          2

In [14]:
customer_data_2 = data_cleaning.clean_invalid_values(customer_data_2)

In [15]:
customer_data_2 = data_cleaning.format_data_types(customer_data_2)

In [16]:
customer_data_2.info()

<class 'pandas.DataFrame'>
RangeIndex: 996 entries, 0 to 995
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   996 non-null    str
 1   state                      996 non-null    str
 2   gender                     991 non-null    str
 3   education                  996 non-null    str
 4   customer_lifetime_value    992 non-null    float64
 5   income                     996 non-null    int64
 6   monthly_premium_auto       996 non-null    int64
 7   number_of_open_complaints  996 non-null    int64
 8   total_claim_amount         996 non-null    float64
 9   policy_type                996 non-null    str
 10  vehicle_class              996 non-null    str
dtypes: float64(2), int64(3), str(6)
memory usage: 85.7 KB

In [17]:
print("File 1:")
customer_data.info()

print("\nFile 2:")
customer_data_2.info()

print("\nFile 3:")
customer_data_3.info()

File 1:
<class 'pandas.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   1071 non-null   str
 1   state                      1071 non-null   str
 2   gender                     954 non-null    str
 3   education                  1071 non-null   str
 4   customer_lifetime_value    1068 non-null   str
 5   income                     1071 non-null   float64
 6   monthly_premium_auto       1071 non-null   float64
 7   number_of_open_complaints  1071 non-null   str
 8   policy_type                1071 non-null   str
 9   vehicle_class              1071 non-null   str
 10  total_claim_amount         1071 non-null   float64
dtypes: float64(3), str(8)
memory usage: 344.6 KB

File 2:
<class 'pandas.DataFrame'>
RangeIndex: 996 entries, 0 to 995
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   996 non-null    str
 1   state                      996 non-null    str
 2   gender                     991 non-null    str
 3   education                  996 non-null    str
 4   customer_lifetime_value    992 non-null    float64
 5   income                     996 non-null    int64
 6   monthly_premium_auto       996 non-null    int64
 7   number_of_open_complaints  996 non-null    int64
 8   total_claim_amount         996 non-null    float64
 9   policy_type                996 non-null    str
 10  vehicle_class              996 non-null    str
dtypes: float64(2), int64(3), str(6)
memory usage: 85.7 KB

File 3:
<class 'pandas.DataFrame'>
RangeIndex: 7070 entries, 0 to 7069
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   7070 non-null   str
 1   state                      7070 non-null   str
 2   customer_lifetime_value    7070 non-null   float64
 3   education                  7070 non-null   str
 4   gender                     7070 non-null   str
 5   income                     7070 non-null   int64
 6   monthly_premium_auto       7070 non-null   int64
 7   number_of_open_complaints  7070 non-null   int64
 8   policy_type                7070 non-null   str
 9   total_claim_amount         7070 non-null   float64
 10  vehicle_class              7070 non-null   str
dtypes: float64(2), int64(3), str(6)
memory usage: 607.7 KB

In [18]:
print("File 1 missing values:")
print(customer_data.isna().sum())

print("\nFile 2 missing values:")
print(customer_data_2.isna().sum())

print("\nFile 3 missing values:")
print(customer_data_3.isna().sum())

File 1 missing values:
customer                     2937
state                        2937
gender                       3054
education                    2937
customer_lifetime_value      2940
income                       2937
monthly_premium_auto         2937
number_of_open_complaints    2937
policy_type                  2937
vehicle_class                2937
total_claim_amount           2937
dtype: int64

File 2 missing values:
customer                     0
state                        0
gender                       5
education                    0
customer_lifetime_value      4
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
total_claim_amount           0
policy_type                  0
vehicle_class                0
dtype: int64

File 3 missing values:
customer                     0
state                        0
customer_lifetime_value      0
education                    0
gender                       0
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
policy_type                  0
total_claim_amount           0
vehicle_class                0
dtype: int64

In [19]:
customer_data = customer_data.dropna(how="all")

In [20]:
customer_data.shape

(1071, 11)

In [21]:
customer_data.isna().sum()

customer                       0
state                          0
gender                       117
education                      0
customer_lifetime_value        3
income                         0
monthly_premium_auto           0
number_of_open_complaints      0
policy_type                    0
vehicle_class                  0
total_claim_amount             0
dtype: int64

In [22]:
customer_data = pd.concat(
    [customer_data, customer_data_2, customer_data_3],
    axis=0
)

customer_data = customer_data.reset_index(drop=True)

In [23]:
customer_data.shape

(9137, 11)

In [24]:
customer_data.isna().sum()

customer                       0
state                          0
gender                       122
education                      0
customer_lifetime_value        7
income                         0
monthly_premium_auto           0
number_of_open_complaints      0
policy_type                    0
vehicle_class                  0
total_claim_amount             0
dtype: int64

In [25]:
customer_data.shape

(9137, 11)

In [26]:
customer_data.duplicated().sum()

np.int64(0)

In [28]:
customer_data["customer_lifetime_value"] = (
    customer_data["customer_lifetime_value"]
    .astype(str)
    .str.replace("%", "", regex=False)
)

customer_data["customer_lifetime_value"] = pd.to_numeric(
    customer_data["customer_lifetime_value"]
)

In [29]:
customer_data["customer_lifetime_value"].dtype

dtype('float64')

In [30]:
customer_data["gender"] = customer_data["gender"].fillna(
    customer_data["gender"].mode()[0]
)

customer_data["customer_lifetime_value"] = customer_data["customer_lifetime_value"].fillna(
    customer_data["customer_lifetime_value"].median()
)

In [31]:
customer_data.isna().sum()

customer                     0
state                        0
gender                       0
education                    0
customer_lifetime_value      0
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
policy_type                  0
vehicle_class                0
total_claim_amount           0
dtype: int64

In [32]:
customer_data.shape

(9137, 11)

In [33]:
customer_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 9137 entries, 0 to 9136
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   9137 non-null   str
 1   state                      9137 non-null   str
 2   gender                     9137 non-null   str
 3   education                  9137 non-null   str
 4   customer_lifetime_value    9137 non-null   float64
 5   income                     9137 non-null   float64
 6   monthly_premium_auto       9137 non-null   float64
 7   number_of_open_complaints  9137 non-null   object
 8   policy_type                9137 non-null   str
 9   vehicle_class              9137 non-null   str
 10  total_claim_amount         9137 non-null   float64
dtypes: float64(4), object(1), str(6)
memory usage: 785.3+ KB

In [34]:
customer_data.head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,F,Master,7.714877e+03,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,6.979536e+05,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1.288743e+06,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,7.645862e+05,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,5.363077e+05,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [35]:
customer_data["number_of_open_complaints"].value_counts(dropna=False)

number_of_open_complaints
0         6425
1          874
1/0/00     830
2          326
3          256
1/1/00     138
4          135
1/2/00      50
5           50
1/3/00      34
1/4/00      13
1/5/00       6
Name: count, dtype: int64

In [36]:
customer_data["number_of_open_complaints"].unique()

array(['1/0/00', '1/2/00', '1/1/00', '1/3/00', '1/5/00', '1/4/00', 0, 1,
       3, 5, 2, 4], dtype=object)

In [37]:
customer_data["number_of_open_complaints"] = (
    customer_data["number_of_open_complaints"]
    .astype(str)
    .str.split("/")
    .str[1]
)

customer_data["number_of_open_complaints"] = pd.to_numeric(
    customer_data["number_of_open_complaints"]
)

In [38]:
customer_data["number_of_open_complaints"].unique()

array([ 0.,  2.,  1.,  3.,  5.,  4., nan])

In [39]:
customer_data["number_of_open_complaints"].dtype

dtype('float64')

In [44]:
customer_data.loc[2067:, "number_of_open_complaints"] = (
    customer_data_3["number_of_open_complaints"].to_numpy()
)

In [46]:
customer_data[customer_data["number_of_open_complaints"].isna()]

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
1071,GS98873,Arizona,F,Bachelor,323912.47,16061.0,88.0,NaN,Personal Auto,Four-Door Car,633.600000
1072,CW49887,California,F,Master,462680.11,79487.0,114.0,NaN,Special Auto,SUV,547.200000
1073,MY31220,California,F,College,899704.02,54230.0,112.0,NaN,Personal Auto,Two-Door Car,537.600000
1074,UH35128,Oregon,F,College,2580706.30,71210.0,214.0,NaN,Personal Auto,Luxury,1027.200000
1075,WH52799,Arizona,F,College,380812.21,94903.0,94.0,NaN,Corporate Auto,Two-Door Car,451.200000
...,...,...,...,...,...,...,...,...,...,...,...
2062,HV85198,Arizona,M,Master,847141.75,63513.0,70.0,NaN,Personal Auto,Four-Door Car,185.667213
2063,BS91566,Arizona,F,College,543121.91,58161.0,68.0,NaN,Corporate Auto,Four-Door Car,140.747286
2064,IL40123,Nevada,F,College,568964.41,83640.0,70.0,NaN,Corporate Auto,Two-Door Car,471.050488
2065,MY32149,California,F,Master,368672.38,0.0,96.0,NaN,Personal Auto,Two-Door Car,28.460568
2066,SA91515,California,M,Bachelor,399258.39,0.0,111.0,NaN,Personal Auto,SUV,700.349052

In [47]:
customer_data["number_of_open_complaints"].isna().sum()

np.int64(996)

In [48]:
customer_data_3["number_of_open_complaints"].isna().sum()

np.int64(0)

In [49]:
customer_data_2["number_of_open_complaints"].head(10)

0    0
1    0
2    0
3    1
4    0
5    0
6    0
7    0
8    0
9    0
Name: number_of_open_complaints, dtype: int64

In [50]:
customer_data_2["number_of_open_complaints"].isna().sum()

np.int64(0)

In [51]:
customer_data.loc[1071:2066, "number_of_open_complaints"] = (
    customer_data_2["number_of_open_complaints"].to_numpy()
)

In [52]:
customer_data.loc[2067:, "number_of_open_complaints"] = (
    customer_data_3["number_of_open_complaints"].to_numpy()
)

In [53]:
customer_data["number_of_open_complaints"].isna().sum()

np.int64(0)

In [54]:
customer_data["number_of_open_complaints"] = (
    customer_data["number_of_open_complaints"].astype(int)
)

In [55]:
customer_data["number_of_open_complaints"].dtype

dtype('int64')

In [56]:
customer_data["gender"].value_counts(dropna=False)

gender
F         4684
M         4369
Male        39
female      28
Femal       17
Name: count, dtype: int64

In [57]:
customer_data["gender"] = customer_data["gender"].replace({
    "Male": "M",
    "female": "F",
    "Femal": "F"
})

In [58]:
customer_data["gender"].value_counts(dropna=False)

gender
F    4729
M    4408
Name: count, dtype: int64

In [59]:
customer_data["state"].value_counts(dropna=False)

state
California    3032
Oregon        2601
Arizona       1679
Nevada         882
Washington     768
Cali           120
WA              30
AZ              25
Name: count, dtype: int64

In [60]:
customer_data["state"] = customer_data["state"].replace({
    "Cali": "California",
    "WA": "Washington",
    "AZ": "Arizona"
})

In [61]:
customer_data["state"].value_counts(dropna=False)

state
California    3152
Oregon        2601
Arizona       1704
Nevada         882
Washington     798
Name: count, dtype: int64

In [62]:
customer_data["education"].value_counts(dropna=False)

education
Bachelor                2736
College                 2682
High School or Below    2616
Master                   752
Doctor                   344
Bachelors                  7
Name: count, dtype: int64

In [63]:
customer_data["education"] = customer_data["education"].replace({
    "Bachelors": "Bachelor"
})

In [64]:
customer_data["education"].value_counts(dropna=False)

education
Bachelor                2743
College                 2682
High School or Below    2616
Master                   752
Doctor                   344
Name: count, dtype: int64

In [65]:
customer_data["vehicle_class"].value_counts(dropna=False)

vehicle_class
Four-Door Car    4641
Two-Door Car     1896
SUV              1774
Sports Car        428
Luxury SUV        161
Luxury Car        145
Luxury             92
Name: count, dtype: int64

In [66]:
customer_data["vehicle_class"] = customer_data["vehicle_class"].replace({
    "Sports Car": "Luxury",
    "Luxury SUV": "Luxury",
    "Luxury Car": "Luxury"
})

In [67]:
customer_data["vehicle_class"].value_counts(dropna=False)

vehicle_class
Four-Door Car    4641
Two-Door Car     1896
SUV              1774
Luxury            826
Name: count, dtype: int64

In [73]:
customer_data.shape
customer_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 9137 entries, 0 to 9136
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   9137 non-null   str
 1   state                      9137 non-null   str
 2   gender                     9137 non-null   str
 3   education                  9137 non-null   str
 4   customer_lifetime_value    9137 non-null   float64
 5   income                     9137 non-null   float64
 6   monthly_premium_auto       9137 non-null   float64
 7   number_of_open_complaints  9137 non-null   int64
 8   policy_type                9137 non-null   str
 9   vehicle_class              9137 non-null   str
 10  total_claim_amount         9137 non-null   float64
dtypes: float64(4), int64(1), str(6)
memory usage: 785.3 KB

In [71]:
customer_data.isna().sum()

customer                     0
state                        0
gender                       0
education                    0
customer_lifetime_value      0
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
policy_type                  0
vehicle_class                0
total_claim_amount           0
dtype: int64

In [72]:
customer_data.duplicated().sum()

np.int64(3)

In [74]:
customer_data[customer_data.duplicated()]

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
1071,GS98873,Arizona,F,Bachelor,323912.47,16061.0,88.0,0,Personal Auto,Four-Door Car,633.6
1072,CW49887,California,F,Master,462680.11,79487.0,114.0,0,Special Auto,SUV,547.2
1073,MY31220,California,F,College,899704.02,54230.0,112.0,0,Personal Auto,Two-Door Car,537.6

In [75]:
customer_data = customer_data.drop_duplicates()
customer_data = customer_data.reset_index(drop=True)

In [76]:
customer_data.duplicated().sum()

np.int64(0)

In [77]:
customer_data.shape

(9134, 11)

# Challenge 2: Structuring Data

In this challenge, we will continue to work with customer data from an insurance company, but we will use a dataset with more columns, called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by performing data cleaning, formatting, and structuring.

In [78]:
# Your code goes here
import pandas as pd

url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv"

marketing_customer_analysis = pd.read_csv(url)

marketing_customer_analysis.head()

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,A,2
1,1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,A,1
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A,2
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,1
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,A,1

In [79]:
marketing_customer_analysis.columns

Index(['unnamed:_0', 'customer', 'state', 'customer_lifetime_value',
       'response', 'coverage', 'education', 'effective_to_date',
       'employmentstatus', 'gender', 'income', 'location_code',
       'marital_status', 'monthly_premium_auto', 'months_since_last_claim',
       'months_since_policy_inception', 'number_of_open_complaints',
       'number_of_policies', 'policy_type', 'policy', 'renew_offer_type',
       'sales_channel', 'total_claim_amount', 'vehicle_class', 'vehicle_size',
       'vehicle_type', 'month'],
      dtype='str')

In [80]:
marketing_customer_analysis.info()

<class 'pandas.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 27 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   unnamed:_0                     10910 non-null  int64
 1   customer                       10910 non-null  str
 2   state                          10910 non-null  str
 3   customer_lifetime_value        10910 non-null  float64
 4   response                       10910 non-null  str
 5   coverage                       10910 non-null  str
 6   education                      10910 non-null  str
 7   effective_to_date              10910 non-null  str
 8   employmentstatus               10910 non-null  str
 9   gender                         10910 non-null  str
 10  income                         10910 non-null  int64
 11  location_code                  10910 non-null  str
 12  marital_status                 10910 non-null  str
 13  monthly_premium_auto           10910 non-null  int64
 14  months_since_last_claim        10910 non-null  float64
 15  months_since_policy_inception  10910 non-null  int64
 16  number_of_open_complaints      10910 non-null  float64
 17  number_of_policies             10910 non-null  int64
 18  policy_type                    10910 non-null  str
 19  policy                         10910 non-null  str
 20  renew_offer_type               10910 non-null  str
 21  sales_channel                  10910 non-null  str
 22  total_claim_amount             10910 non-null  float64
 23  vehicle_class                  10910 non-null  str
 24  vehicle_size                   10910 non-null  str
 25  vehicle_type                   10910 non-null  str
 26  month                          10910 non-null  int64
dtypes: float64(4), int64(6), str(17)
memory usage: 2.2 MB

In [81]:
marketing_customer_analysis.isna().sum()

unnamed:_0                       0
customer                         0
state                            0
customer_lifetime_value          0
response                         0
coverage                         0
education                        0
effective_to_date                0
employmentstatus                 0
gender                           0
income                           0
location_code                    0
marital_status                   0
monthly_premium_auto             0
months_since_last_claim          0
months_since_policy_inception    0
number_of_open_complaints        0
number_of_policies               0
policy_type                      0
policy                           0
renew_offer_type                 0
sales_channel                    0
total_claim_amount               0
vehicle_class                    0
vehicle_size                     0
vehicle_type                     0
month                            0
dtype: int64

In [82]:
marketing_customer_analysis[
    ["sales_channel", "monthly_premium_auto", "total_claim_amount"]
].head()

  sales_channel  monthly_premium_auto  total_claim_amount
0         Agent                    61          292.800000
1   Call Center                    64          744.924331
2   Call Center                   100          480.000000
3        Branch                    97          484.013411
4        Branch                   117          707.925645

In [83]:
marketing_customer_analysis["sales_channel"].value_counts()

sales_channel
Agent          4121
Branch         3022
Call Center    2141
Web            1626
Name: count, dtype: int64

In [84]:
marketing_customer_analysis.pivot_table(
    index="sales_channel",
    values="monthly_premium_auto",
    aggfunc="sum"
).round(2)

               monthly_premium_auto
sales_channel
Agent                        386335
Branch                       280953
Call Center                  197970
Web                          151511

The Agent channel has the highest total monthly premium, with 386,335, followed by Branch with 280,953. The Web channel has the lowest total monthly premium, with 151,511. This suggests that the Agent channel contributes the most in total monthly premiums among the four sales channels in this dataset.

In [85]:
marketing_customer_analysis.pivot_table(
    index="gender",
    columns="education",
    values="customer_lifetime_value",
    aggfunc="mean"
).round(2)

education  Bachelor  College   Doctor  High School or Below   Master
gender
F           7874.27  7748.82  7328.51               8675.22  8157.05
M           7703.60  8052.46  7415.33               8149.69  8168.83

The pivot table shows the average customer lifetime value by gender and education level. Female customers with High School or Below education have the highest average CLV, at 8,675.22. Customers with a Doctorate have the lowest average CLV for both genders. The results also show that the difference between males and females depends on their education level, so neither gender has a higher average CLV across every category.

1. You work at the marketing department and you want to know which sales channel brought the most sales in terms of total revenue. Using pivot, create a summary table showing the total revenue for each sales channel (branch, call center, web, and mail).
Round the total revenue to 2 decimal points.  Analyze the resulting table to draw insights.

2. Create a pivot table that shows the average customer lifetime value per gender and education level. Analyze the resulting table to draw insights.

## Bonus

You work at the customer service department and you want to know which months had the highest number of complaints by policy type category. Create a summary table showing the number of complaints by policy type and month.
Show it in a long format table.

*In data analysis, a long format table is a way of structuring data in which each observation or measurement is stored in a separate row of the table. The key characteristic of a long format table is that each column represents a single variable, and each row represents a single observation of that variable.*

*More information about long and wide format tables here: https://www.statology.org/long-vs-wide-data/*

In [86]:
# Your code goes here
marketing_customer_analysis[
    ["policy_type", "month", "number_of_open_complaints"]
].head()

      policy_type  month  number_of_open_complaints
0  Corporate Auto      2                   0.000000
1   Personal Auto      1                   0.000000
2   Personal Auto      2                   0.000000
3  Corporate Auto      1                   0.000000
4   Personal Auto      1                   0.384256

In [87]:
marketing_customer_analysis["has_complaint"] = (
    marketing_customer_analysis["number_of_open_complaints"] > 0
)

complaints_by_policy_month = marketing_customer_analysis.pivot_table(
    index=["policy_type", "month"],
    values="has_complaint",
    aggfunc="sum"
).reset_index()

complaints_by_policy_month = complaints_by_policy_month.rename(
    columns={"has_complaint": "number_of_complaints"}
)

complaints_by_policy_month

      policy_type  month  number_of_complaints
0  Corporate Auto      1                   314
1  Corporate Auto      2                   268
2   Personal Auto      1                  1102
3   Personal Auto      2                   965
4    Special Auto      1                    51
5    Special Auto      2                    50

In [88]:
complaints_by_policy_month.sort_values(
    by="number_of_complaints",
    ascending=False
)

      policy_type  month  number_of_complaints
2   Personal Auto      1                  1102
3   Personal Auto      2                   965
0  Corporate Auto      1                   314
1  Corporate Auto      2                   268
4    Special Auto      1                    51
5    Special Auto      2                    50

The results show that Personal Auto had the highest number of customers with open complaints in both months. Month 1 had more customers with complaints than month 2 across all three policy types. Special Auto had the lowest numbers, with 51 customers in month 1 and 50 in month 2. This suggests that customer complaints were most common among Personal Auto customers during month 1.